default: &default
  adapter: postgresql
  encoding: unicode
  host: db  # Matches the Docker Compose service name
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: airbnb_main_development

test:
  <<: *default
  database: airbnb_main_test

production:
  <<: *default
  database: airbnb_main_production
